# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  langueeduapi:
    image: langueeduapi
    build:
      context: .
      dockerfile: src/Services/Langueedu.API/Dockerfile

  blazor:
    image: blazor
    depends_on:
      - langueeduapi
    build:
      context: .
      dockerfile: src/Web/Langueedu.Web/Server/Dockerfile.dev
