version: '3.4'

services:
  langueeduapi:
    image: langueeduapi
    build:
      context: .
      dockerfile: src/Services/Langueedu.API/Dockerfile

  blazor:
    image: blazor
    depends_on:
      - langueeduapi
    build:
      context: .
      dockerfile: src/Web/Langueedu.Web/Server/Dockerfile.dev
