FROM mcr.microsoft.com/dotnet/sdk:6.0 AS base
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src

COPY ["src/Web/Langueedu.Web/Client/Langueedu.Web.Client.csproj", "Client/"]
COPY ["src/Web/Langueedu.Web/Langueedu.Web.Components/Langueedu.Web.Components.csproj", "Web/Langueedu.Web/Langueedu.Web.Components/"]
COPY ["src/Web/Langueedu.Web/Langueedu.Web.Pages/Langueedu.Web.Pages.csproj", "Web/Langueedu.Web/Langueedu.Web.Pages/"]
COPY ["src/Web/Langueedu.Web/Shared/Langueedu.Web.Shared.csproj", "Web/Langueedu.Web/Shared/"]
COPY ["src/Shared/Langueedu.Sdk/Langueedu.Sdk.csproj", "Shared/Langueedu.Sdk/"]
COPY ["src/Web/Langueedu.Web/Server/Langueedu.Web.Server.csproj", "Web/Langueedu.Web/Server/"]

FROM base AS restore
RUN dotnet restore Web/Langueedu.Web/Server/Langueedu.Web.Server.csproj -nowarn:msb3202,nu1503

COPY . .

FROM restore AS build
RUN dotnet build -c $BUILD_CONFIGURATION
# RUN dotnet build  "./src/Web/Langueedu.Web/Server/Langueedu.Web.Server.csproj" -c $BUILD_CONFIGURATION

ENTRYPOINT ["dotnet", "run", "--no-build", "--no-launch-profile", "-c", "$BUILD_CONFIGURATION", "--"]
